export const WEWRITE_MOCK_MODE_ENV = 'WECHAT_CLI_BRIDGE_WEWRITE_MOCK_MODE';

function normalizeFlag(value: string | undefined): boolean {
  if (!value) {
    return false;
  }

  return ['1', 'true', 'yes', 'on'].includes(value.trim().toLowerCase());
}

export function isWeWriteMockModeEnabled(): boolean {
  return normalizeFlag(process.env[WEWRITE_MOCK_MODE_ENV]);
}

export async function materializeMockWritingArtifacts(options: {
  route: 'article_create' | 'article_edit';
  topic: string;
  requestText: string;
  outlinePath: string;
  draftPath: string;
  previewPath: string;
  skillPath: string | null;
}): Promise<void> {
  const title = `${options.topic}：从问题到落地`;
  const outline = [
    '# Outline',
    '',
    `- 标题建议：${title}`,
    '- 开场：问题背景与场景',
    '- 核心判断：为什么这件事值得现在做',
    '- 方法拆解：实现路径 / 策略 / 注意事项',
    '- 落地建议：下一步行动项',
    '',
    '> Generated by WeWrite mock mode for local UAT.',
    '',
  ].join('\n');

  const draft = [
    `# ${title}`,
    '',
    '> Generated by WeWrite mock mode for local UAT.',
    '',
    '## 开场',
    `${options.requestText}。这类主题适合先把问题边界说清，再进入方法与落地部分。`,
    '',
    '## 核心判断',
    `${options.topic} 不是一个抽象概念，它直接影响执行效率、风险控制和交付质量。`,
    '',
    '## 方法拆解',
    options.route === 'article_edit'
      ? '本次任务偏向“改写 / 润色”，因此 mock 模式保留原有结构思路，强调标题、段落节奏和表达收敛。'
      : '本次任务偏向“从零起稿”，因此 mock 模式给出标题、结构提纲和可直接扩展的正文骨架。',
    '',
    '## 落地建议',
    '- 先确认读者对象与目标场景',
    '- 再补 2 到 3 个真实案例',
    '- 最后统一标题、摘要和结尾行动项',
    '',
    '## 备注',
    `- WeWrite skill: ${options.skillPath || '(mock mode without real skill)'}`,
    '- 当前输出用于本地 article lane UAT，不代表真实 WeWrite 最终质量。',
    '',
  ].join('\n');

  const fs = await import('fs-extra');
  await fs.writeFile(options.outlinePath, outline, 'utf8');
  await fs.writeFile(options.draftPath, draft, 'utf8');
  const { materializeWeChatPreviewHtml } = await import('./preview');
  await materializeWeChatPreviewHtml({
    draftPath: options.draftPath,
    previewPath: options.previewPath,
  });
}
