import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { initStorage, resetStorageForTests, storage } from '../utils/storage';
import { resetLoggerForTests } from '../utils/logger';
import { WeWriteAdapter, resolveWritingAgentName } from './wewrite-adapter';
import { WEWRITE_MOCK_MODE_ENV } from './mock-runner';

const TEST_DIR = path.join(
  os.tmpdir(),
  'wechat-cli-bridge-wewrite-test',
  Date.now().toString()
);

describe('WeWriteAdapter', () => {
  beforeEach(() => {
    initStorage(TEST_DIR);
  });

  afterEach(async () => {
    delete process.env.WEWRITE_SKILL_PATH;
    delete process.env[WEWRITE_MOCK_MODE_ENV];
    resetStorageForTests();
    resetLoggerForTests();
    await fs.remove(TEST_DIR);
  });

  it('should prefer claude/openclaw agents for writing workflows', () => {
    expect(resolveWritingAgentName('codex', ['codex', 'claude'])).toBe('codex');
    expect(resolveWritingAgentName('openclaw', ['openclaw'])).toBe('openclaw');
    expect(resolveWritingAgentName('codex', ['codex'])).toBe('codex');
    expect(resolveWritingAgentName('iflow', ['codex'])).toBe('codex');
  });

  it('should create article artifacts even when WeWrite is missing', async () => {
    process.env.WEWRITE_SKILL_PATH = path.join(TEST_DIR, 'missing-wewrite');
    const adapter = new WeWriteAdapter();

    const result = await adapter.prepareWorkflow({
      route: 'article_create',
      requestText: '写一篇关于 AI 路由的公众号文章',
      userId: 'user-1',
      jobId: 'job-1',
      workingDir: '/tmp/project',
      defaultAgent: 'codex',
      availableAgents: ['codex'],
    });

    expect(result.status).toBe('integration_missing');
    expect(result.message).toContain('未检测到本地 WeWrite');
    expect(result.artifacts).toHaveLength(7);
    expect(await fs.pathExists(path.join(storage.sessionsDir, 'user-1', 'artifacts', 'job-1', 'article-brief.md'))).toBe(true);
    expect(await fs.pathExists(path.join(storage.sessionsDir, 'user-1', 'artifacts', 'job-1', 'wechat-preview.html'))).toBe(true);
    expect(await fs.pathExists(path.join(storage.sessionsDir, 'user-1', 'artifacts', 'job-1', 'image-plan.json'))).toBe(true);
  });

  it('should prepare a ready workflow when WeWrite and claude are available', async () => {
    const skillDir = path.join(TEST_DIR, 'fake-wewrite');
    await fs.ensureDir(skillDir);
    process.env.WEWRITE_SKILL_PATH = skillDir;
    const adapter = new WeWriteAdapter();

    const result = await adapter.prepareWorkflow({
      route: 'article_create',
      requestText: '写一篇关于 AI 路由的公众号文章',
      userId: 'user-2',
      jobId: 'job-2',
      workingDir: '/tmp/project',
      defaultAgent: 'claude',
      availableAgents: ['claude', 'codex'],
    });

    expect(result.status).toBe('ready');
    expect(result.agentName).toBe('claude');
    expect(result.artifactDir).toBe(
      path.join(storage.sessionsDir, 'user-2', 'artifacts', 'job-2')
    );
    expect(result.prompt).toContain(skillDir);
    expect(result.prompt).toContain('outline.md');
    expect(result.artifacts).toHaveLength(7);
  });

  it('should complete locally when WeWrite mock mode is enabled', async () => {
    process.env[WEWRITE_MOCK_MODE_ENV] = 'true';
    const adapter = new WeWriteAdapter();

    const result = await adapter.prepareWorkflow({
      route: 'article_create',
      requestText: '写一篇关于 AI 路由的公众号文章',
      userId: 'user-3',
      jobId: 'job-3',
      workingDir: '/tmp/project',
      defaultAgent: 'codex',
      availableAgents: ['codex'],
    });

    const artifactDir = path.join(storage.sessionsDir, 'user-3', 'artifacts', 'job-3');
    expect(result.status).toBe('completed_local');
    expect(result.message).toContain('mock mode');
    expect(await fs.readFile(path.join(artifactDir, 'outline.md'), 'utf8')).toContain('Generated by WeWrite mock mode');
    expect(await fs.readFile(path.join(artifactDir, 'draft.md'), 'utf8')).toContain('AI 路由');
    expect(await fs.readFile(path.join(artifactDir, 'wechat-preview.html'), 'utf8')).toContain('微信文章预览');
  });
});
